### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by MSG100TC** [armagadon159753/AdminUI#4]
Adding Pictures for BAN, and KICK UI!!

That'll be awesome XD

**Comment by armagadon159753** [comment]
Look like wat?

**Comment by MSG100TC** [comment]
For example, the Redstone block picture can be the "BAN" button's picture.

**Comment by MSG100TC** [comment]
For example, the blocks beside it can be the picture for the action:

 ![example3](https://user-images.githubusercontent.com/19265943/33554194-ac57b200-d936-11e7-8dcc-d59a67a40dfb.png)

Btw, can you add another config specialised for editing UI images?

**Comment by armagadon159753** [comment]
OK thank 
I will make server after AdminUI ^~^

**Comment by MSG100TC** [comment]
You will make a server?

**Comment by armagadon159753** [comment]
Server Selector

**Comment by MSG100TC** [comment]
Nice!!

Btw, can you add the "Tempban" and "Tempmute" feature in AdminUI?

**Comment by armagadon159753** [comment]
Dont worry i will keep this plugin update but i m make CrateKey plugin ^~^

**Comment by MSG100TC** [comment]
Thanks!

**Comment by MSG100TC** [comment]
One more request, Can you add permissions for AdminUI?

**Comment by daniel022302** [comment]
tempban

**Comment by armagadon159753** [comment]
#5
